sudo: required
language: python
python:
  - "3.6"
cache: pip
services:
  - docker
install:
  - pip install unittest2
script:
  - python calculadora.py
  - python -m unittest test_calc.py
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t calculadora .
  - docker tag calculadora:latest 199886244715.dkr.ecr.us-east-1.amazonaws.com/calculadora:latest
  - docker push 199886244715.dkr.ecr.us-east-1.amazonaws.com/calculadora:latest

  env:
  global:
  - DOCKER_REPO=myorg/veryimportantimage
  - EB_REGION="us-east-1"
  - secure: travisEncryptedAWS_ACCOUNT_ID
  - secure: travisEncryptedAWS_ACCESS_KEY_ID
  - secure: travisEncryptedAWS_SECRET_ACCESS_KEY