sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
global:
  - DOCKER_REPO=calculadora
  - EB_REGION="us-east-1"
  - secure: $AWS_ACCOUNT_ID
  - secure: $AWS_ACCESS_KEY_ID
  - secure: $AWS_SECRET_ACCESS_KEY
install:
  - pip install unittest2
script:
  - python calculadora.py
  - python -m unittest test_calc.py
after_success:
  - docker --version
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t calculadora .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master