sudo: required
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install unittest2
script:
  - python calculadora.py
  - python -m unittest test_calc.py
after_success:
  - docker --version
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t calculadora .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master